services:
  ssh:
    container_name: home-folder
    build:
      context: .
    ports:
      - 2000:22 
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128M"
    restart: unless-stopped
